server:
  port: 8090
  shutdown: graceful
logging:
  level:
    top.abosen.thrift: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
spring:
  thrift:
    client:
      mark: abcd
      services:
        -
          service-name: calculator-thrift-service
          package-to-scan: top.abosen.thrift.demo.calculator
        -
          service-name: calculator-thrift-service2
          package-to-scan: top.abosen.thrift.demo.calculator2
